name: zcord
description: "Discord analog"
publish_to: 'none' # Удалите эту строку, если хотите опубликовать на pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0  # No need to override firebase_auth_web here
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  awesome_dialog: ^3.2.1
  cloud_firestore: ^5.6.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
  assets:
    - assets/zcord_logo.png
    - assets/lang/
