name: zcord
description: "A new Flutter project."
publish_to: 'none' # Удалите эту строку, если хотите опубликовать на pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0
  postgres: ^2.3.0
  http: ^0.13.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
  assets:
    - assets/zcord_logo.png
    - assets/lang/