// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA0zVRg_u_zNZ53eu7i_BKA3g-EbYSWfY',
    appId: '1:1052939828410:web:37f496e2fec864a56a9683',
    messagingSenderId: '1052939828410',
    projectId: 'z-cord-50702',
    authDomain: 'z-cord-50702.firebaseapp.com',
    storageBucket: 'z-cord-50702.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNaA4O1x19G0wVG1RDWkRdluRBhNxoik',
    appId: '1:1052939828410:android:eced331d45ad03156a9683',
    messagingSenderId: '1052939828410',
    projectId: 'z-cord-50702',
    storageBucket: 'z-cord-50702.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA0zVRg_u_zNZ53eu7i_BKA3g-EbYSWfY',
    appId: '1:1052939828410:web:a2a14b647b61be896a9683',
    messagingSenderId: '1052939828410',
    projectId: 'z-cord-50702',
    authDomain: 'z-cord-50702.firebaseapp.com',
    storageBucket: 'z-cord-50702.firebasestorage.app',
  );
}
